# Generated by Django 2.2.28 on 2023-06-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
